name: ✨Feature Request
description: File a bug report.
title: "✨[feat] "
labels: ["feat"]
assignees:
  - BernieHuang2008
body:
  - type: input
    id: feat_name
    attributes:
      label: Feature Name
      description: Does the feature have a name?
      placeholder: e.g. Unified Error
    validations:
      required: true
  - type: textarea
    id: feat_desc
    attributes:
      label: A brief introduction of the feature.
    validations:
      required: true
  - type: checkboxes
    id: feat_cate
    attributes:
      description: What will be new if the feature is implemented?
      options:
        - label: New API
  - type: markdown
    id: feat_extra
    attributes:
      description: Are there anything else?
  
